---
title: "`r paste('Flo:', param$name)`"
author: "Florian Vetsch"
output: 
  html_document:
    self_contained: false
    lib_dir: rmarkdownLib
    includes:
      in_header: fgcz_header.html
    css: fgcz.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(magrittr)
```
Started on `r format(Sys.time(), "%Y-%m-%d %H:%M:%S")`

foo bar hoge

## Flo_Result {.tabset}

### Number of SNPs

```{r SNP counts, fig.width=8, fig.height=5, echo=FALSE, message=FALSE, warning=FALSE}
data <- read.table(snp_counts, sep="\t", skip=2)
names(data) <- c("Counts", "Sample")
samples <- gsub("samples/", "", data$Sample)
plot_ly(data, x = samples, y = data$Counts)
```
### PCA tryouts

Summary
```{r, fig.width=8, fig.height=5, echo=FALSE, message=FALSE, warning=FALSE}
snpgdsSummary("snp.gds")
```

Percentage of variance explained per additional PC
```{r, echo=FALSE, message=FALSE, warning=FALSE}
vars_sum
```

Plotting the first 3 PCs
```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(df, aes(x = EV1, y = EV2, colour = EV3)) +
  geom_point(alpha=0.5) +
  geom_text(label=df$sample.id, size = 1, check_overlap=T,
            nudge_y = 0.05) +
  theme_bw()
```

Plot the first 2 PCs with sample ID as labels
```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(df, aes(x = EV1, y = EV2, label = sample.id)) +
  geom_point(alpha=0.5, colour="blue", size = 1) +
  geom_text_repel(size = 1, min.segment.length = 0, box.padding = 0.7,
                  max.overlaps = 100,
                  segment.size= 0.1,
                  segment.linetype = "dashed",
                  segment.alpha = 0.5) +
  theme_bw()
```


### Input Dataset
```{r, echo=FALSE, message=FALSE}
ezInteractiveTableRmd(values=ans4Report[["dataset"]])
```

### SessionInfo
```{r, echo=FALSE}
sessionInfo()
```
